/*
SQLyog Community v12.2.6 (64 bit)
MySQL - 10.4.11-MariaDB : Database - u3196890_ipc
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `artikel` */

DROP TABLE IF EXISTS `artikel`;

CREATE TABLE `artikel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `judul` text DEFAULT NULL,
  `desc` text DEFAULT NULL,
  `tanggal` date DEFAULT NULL,
  `foto` text DEFAULT NULL,
  `visit` int(11) DEFAULT 0,
  `stat` enum('Show','Hidden','Unset') DEFAULT 'Unset',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

/*Data for the table `artikel` */

insert  into `artikel`(`id`,`judul`,`desc`,`tanggal`,`foto`,`visit`,`stat`) values 
(5,'Bagaimana Menyikapi Penyakit COVID-19?','<p>Bagaimana kita bisa waspada, namun tidak panik?</p><p>Untuk masyarakat awam, pencegahan penularan COVID-19 bisa dilakukan dengan cara-cara yang sederhana:</p><p>&nbsp; &nbsp; &nbsp;1. Hindari Tempat Keramaian</p><p>&nbsp; &nbsp; &nbsp;Peluang anda untuk berkontak dengan penderita COVID-19 (dan manusia secara umum) akan berkurang. Karena tidak semua penderita menunjukkan gejala sakit (asimptomatik), dan bisa saja menularkan penyakit. Batalkan atau tunda perjalanan jauh selama wabah.</p><p>&nbsp; &nbsp; &nbsp;2. Cuci tangan dengan sabun dan air mengalir</p><p>&nbsp; &nbsp; &nbsp;Cucilah tangan dengan air mengalir untuk menghilangkan kuman. Terutama setelah memegang barang-barang di fasilitas umum, dan sebelum makan atau minum. Sabun bisa melarutkan kotoran lemak yang bisa ditumpangi kuman dan merusak struktur lemak pada kuman. Sabun dan air mengalir lebih efektif mencegah penyakit daripada cairan pembersih tangan berbasis alkohol. Menurut CDC (Center for Disease Control), pilihan pertama adalah mencuci tangan dengan sabun dan air mengalir. Dalam kondisi tidak ada air dan sabun, cairan <i>hand sanitizer</i> bisa digunakan. Jadi bukan mempunyai fungsi yang saling mengganti.&nbsp;</p><p>&nbsp; &nbsp; &nbsp;3. Praktikkan etika batuk dan bersin yang benar</p><p>&nbsp; &nbsp; &nbsp;Bila anda sakit, tutuplah hidung dan mulut dengan tisu, dan langsung dibuang bila kotor. Atau dapat menggunakan bagian dalam lengan atas untuk menutup hidung dan mulut saat batuk dan bersin. Gunakan masker bila bepergian saat anda sakit untuk mencegah penularan melalui droplet. Bila sakit berlanjut disertai dengan demam dan sesak napas, segera berobat ke dokter agar bisa diperiksa lebih lanjut.</p><p>Mari sama-sama bantu cegah penularan penyakit COVID-19<br><br>&nbsp;</p>','2020-03-03','photo6262331968955984559.jpg',1,'Show'),
(6,'It\'s Sunnah #2','<p>&nbsp;</p><p>Dari Anas bin Malik bahwa Rasulullah SAW berdoa:<br>“Ya Allah, aku berlindung kepadaMu dari penyakit kulit, gila, lepra dan dari penyakit lain yang mengerikan.” (HR Abu Dawud)</p><p><br>Pada saat adanya wabah penyakit seperti ini, kita disunnahkan untuk memohonkan doa kepada Allah untuk dilindungi dari penyakit yang berbahaya. Tentu harus dibarengi ikhtiar agar tidak meninggalkan sebab untuk dilindungi dari penyakit.&nbsp;</p><p><br>Beberapa langkah pencegahan yang dapat dilakukan:</p><ol><li>Sering mencuci tangan dengan sabun dan air mengalir</li><li>Mempraktikkan etika batuk dan bersih yang benar</li><li>Menjauhi tempat keramaian</li><li>Makan makanan yang sudah dimasak dengan matang</li><li>Mengamalkan pola hidup bersih dan sehat secara umum</li></ol>','2020-03-05','photo6265044180673866016.jpg',1,'Show'),
(7,'It\'s Sunnah #3','<p>Setiap informasi yang datang kepada kita hendaklah diteliti, diklarifikasi dan dipastikan keabsahannya sebelum diterima. Saat ada wabah, keadaan akan sangat rentan untuk beredarnya hoax/kabar palsu yang bisa menciptakan suasana panik dan ketakutan yang berlebihan.&nbsp;<br><br>Di dalam Al-Quran, Allah berfirman:<br>Wahai orang- orang yang beriman, jika ada seorang faasiq datang kepada kalian dengan membawa suatu berita penting, maka tabayyunlah (telitilah dulu), agar jangan sampai kalian menimpakan suatu bahaya pada suatu kaum atas dasar kebodohan, kemudian akhirnya kalian menjadi menyesal atas perlakuan kalian. (QS Al Hujurat: 6)<br><br>Yuk, cek dan ricek semua info atau pesan yang sampai kepada kita, sebelum dengan mudah langsung membagikan dengan orang lain. Pastikan semua informasi yang sampai berasal dari sumber yang bisa dipertanggungjawabkan. Khususnya untuk informasi terkini tentang COVID-19, dapat dilihat di <a href=\"http://www.infeksiemerging.kemkes.go.id/\">www.infeksiemerging.kemkes.go.id</a> atau <a href=\"http://www.who.int/emergencies/diseases/novel-coronavirus-2019/events-as-they-happen\">www.who.int/emergencies/diseases/novel-coronavirus-2019/events-as-they-happen</a></p>','2020-03-06','photo6269157625472067941.jpg',1,'Show'),
(8,'It\'s Sunnah #4','<p>Sesungguhnya sifat orang yang beriman itu hatinya lembut dan peka. Ia tidak hanya peduli sesama manusia, bahkan semua makhluk Allah.<br><br>“Mereka yang baik dan memperhatikan makhluk-makhluk Allah, Allah melimpahkan kebaikan dan kasih sayang-Nya kepada mereka. Tunjukkan kasih sayang kepada yang ada di Bumi, niscaya kalian akan dirahmati oleh Zat yang ada di langit.” (HR Abu Dawud No 4941 dan At Tirmizi No 1924).<br><br>Bagaimana implementasi hadits di atas dalam kehidupan kita? Kita dituntut untuk peka dan peduli antar sesama, dan tidak hanya mementingkan diri sendiri. Di saat sedang ada wabah penyakit seperti sekarang, beberapa hal yang bisa kita lakukan:<br>&nbsp;</p><ol><li>Tidak menimbun bahan makanan atau kebutuhan pokok lain</li><li>Tidak menimbun masker atau cairan pembersih tangan</li><li>Menawarkan bantuan kepada yang memerlukan</li><li>Menyumbangkan tenaga/harta/waktu dan lain-lain untuk membantu sesama</li><li>Berhati-hati dalam menyebar informasi agar tidak menyebabkan kepanikan atau ketakutan yang berlebihan<br>&nbsp;</li></ol><p>Mari peka dan peduli terhadap sesama. It’s Sunnah!</p>','2020-03-07','photo6269217978352511351.jpg',1,'Show'),
(9,'It\'s Sunnah #1','<p>Nabi Muhammad SAW juga pernah memperingatkan umatnya untuk jangan berada dekat wilayah yang sedang terkena wabah. Sebaliknya jika berada di dalam tempat yang terkena wabah dilarang untuk keluar.</p><p><br>Hadits yang dinarasikan Abdullah bin \'Amir mengatakan:</p><p><br>\"Umar sedang dalam perjalanan menuju Syam, saat sampai di wilayah bernama Sargh. Saat itu Umar mendapat kabar adanya wabah di wilayah Syam. Abdurrahman bin Auf kemudian mengatakan pada Umar jika Nabi Muhammad SAW pernah berkata, \"Jika kamu mendengar wabah di suatu wilayah, maka janganlah kalian memasukinya. Namun, jika suatu wabah menjangkiti suatu negeri dan kalian sedang berada di dalamnya, maka jangan tinggalkan tempat itu.\" (Shahih, HR Bukhari No 5288).</p><p><br>Bertepatan dengan kondisi global saat ini, maka hendaklah kita mengamalkan anjuran Nabi ini. Indonesia juga sudah melaporkan kasus positif sejak 2 Maret 2020. Sedapat mungkin batalkan atau tunda rencana perjalanan jauh yang bisa meningkatkan risiko penularan di tempat keramaian seperti bandara, stasiun, dan terminal. Apalagi mengunjungi negara-negara yang sudah melaporkan banyaknya kasus positif infeksi COVID-19.&nbsp;</p><p><br>Karantina merupakan salah satu upaya pencegahan penyakit yang sangat efektif. Masyarakat umum bisa membantu meringankan situasi wabah saat ini dengan tidak panik, tidak mengunjungi tempat keramaian, berempati dengan sesama, dan mengikuti panduan yang sudah disampaikan oleh pemerintah.</p>','2020-03-04','photo6264583768769669526.jpg',1,'Show'),
(10,'PERLUKAH KITA MENGGUNAKAN MASKER?','<p>Pengumuman tentang 2 orang pasien positif COVID-19 di Indonesia sebagaimana yang disampaikan oleh Presiden RI pada 2 Maret 2020 langsung menuai kepanikan dari masyarakat. Orang berbondong-bondong membeli masker yang berakibat kelangkaan terjadi di tengah masyarakat sehingga harga masker melesat hingga 10 kali lipat bahkan lebih.<br><br>Kita perlu waspada terhadap COVID-19, namun tidak boleh panik. Memang ia penyakit yang mudah menular tapi dapat dicegah. Mari bijak menggunakan masker, Sahabat Sehat. Masker berfungsi untuk mencegah droplet orang sakit dari menular ke orang yang sakit. &nbsp;Jangan sampai penderita yang sakit justru tidak memperoleh masker sehingga potensi penyebaran penyakitnya semakin meluas.&nbsp;</p><p><br>Bagi kita yang sehat dan tidak mengalami gangguan pernapasan, penggunaan masker tidak selalu diperlukan. Merutinkan cuci tangan, mempraktikkan etika batuk dan bersin yang benar, serta menjaga gaya hidup sehat lebih efektif mencegah penyebarannya.<br><br>Lalu, Kapan sebenarnya kita perlu menggunakan masker?<br>&nbsp;</p><ol><li>Bila kita mengalami gejala gangguan pernapasan seperti batuk, pilek atau sesak nafas</li><li>Bila kita merawat orang dengan gangguan pernapasan</li><li>Bagi tenaga kesehatan yang menangani pasien dengan gangguan pernapasan</li></ol><p><br><br>Dan yang terpenting, hindari tempat-tempat keramaian ya!<br><br><a href=\"tg://search_hashtag?hashtag=coronavirus\">#coronavirus</a> <a href=\"tg://search_hashtag?hashtag=covid19\">#covid19</a> <a href=\"tg://search_hashtag?hashtag=masker\">#masker</a> <a href=\"tg://search_hashtag?hashtag=batuk\">#batuk</a> <a href=\"tg://search_hashtag?hashtag=pilek\">#pilek</a> <a href=\"tg://search_hashtag?hashtag=sesaknafas\">#sesaknafas</a> <a href=\"tg://search_hashtag?hashtag=edukasi\">#edukasi</a> <a href=\"tg://search_hashtag?hashtag=kesehatan\">#kesehatan</a>&nbsp;</p>','2020-03-04','photo6267267719602743734.jpg',1,'Show'),
(12,'It\'s Sunnah #5','<p>Salah satu dari intervensi kesehatan yang paling efektif adalah mencuci tangan. Tangan kita bisa menjadi sumber penularan penyakit yang paling besar. Karena kuman (virus, bakteri dan parasit) tidak kasat mata, maka kadang-kadang kita tidak sadar bahwa tangan kita kotor.<br><br>Dari Abu Hurairah, bahwa Rasulullah SAW bersabda:<br>“Jika salah seorang dari kalian berwudhu, hendaklah ia memasukkan air ke dalam hidung lalu mengeluarkannya (istinsyaq), barangsiapa yang beristinja’ dengan batu (istijmar) hendaklah dengan bilangan ganjil, dan jika salah seorang dari kalian bangun dari tidurnya, hendaklah ia membasuh kedua telapak tangannya sebelum memasukkannya dalam bejana air wudhunya, sebab salah seorang dari kalian tidak mengetahui dimana tangannya bermalam.” (HR Al Bukhari)<br><br>Mencuci tangan dengan air mengalir akan menghilangkan kotoran dan kuman dari tangan kita. Dan bila disertai dengan penggunaan sabun, dapat membunuh kuman karena sabun merusak lapisan lemak pada struktur kuman.&nbsp;<br><br>Sering-sering mencuci tangan dengan sabun dan air mengalir di masa-masa wabah seperti sekarang, terutama setelah menyentuh benda-benda di tempat umum.&nbsp;<br><br>Yuk cegah penularan penyakit dengan mencuci tangan. It’s Sunnah!</p>','2020-03-08','photo6267267719602743771.jpg',1,'Show'),
(13,'It\'s Sunnah #6','<p>Pemerintah sedang mengkampanyekan Gerakan Masyarakat Hidup Sehat (GERMAS) sebagai salah satu upaya untuk menjaga kesehatan diri dan keluarga, khususnya untuk mencegah penularan wabah penyakit. Salah satu komponen yang penting dari GERMAS adalah menjaga kebersihan.&nbsp;<br><br>Diriwayatkan dari Saad bin Abi Waqqas dari bapaknya, dari Rasulullah SAW:<br>“Sesungguhnya Allah SWT itu suci yang menyukai hal-hal yang suci, Dia Maha Bersih yang menyukai kebersihan, Dia Maha Mulia yang menyukai kemuliaan, Dia Maha Indah yang menyukai keindahan, karena itu bersihkanlah tempat-tempatmu” (HR. Tirmizi)<br><br>Beberapa anjuran dari GERMAS yang dapat kita lakukan:</p><ol><li>Menjaga kebersihan lingkungan&nbsp;</li><li>Mencuci tangan dengan sabun dan air mengalir</li><li>Mempraktikkan etika batuk dan bersin yang benar</li><li>Tidak merokok</li><li>Masak masakan sampai betu-betul matang</li><li>Makan dengan gizi seimbang</li></ol><p>Rajin berolahraga dan istirahat cukup<br><br>Jaga kebersihan untuk mencegah penularan penyakit. It’s Sunnah!</p>','2020-03-09','photo6267267719602743770.jpg',4,'Show'),
(14,'WORKSHOP PENANGGULANGAN KEBAKARAN, MANAJEMEN BENCANA DAN SIMULASI EVAKUASI','<p>Guna memenuhi salah satu persyaratan dalam akreditasi klinik, IMANI Primary Care memberikan kesempatan untuk kamu yang sedang dalam proses menuju Klinik Akreditasi Paripurna untuk mengikuti workshop yang akan dilaksanakan pada:<br>&nbsp;</p><ul><li>Waktu : Jumat-Sabtu, 27-28 Maret 2020</li><li>Pukul : 08.00 sd 16.00 WIB</li><li>Tempat : Ruang Rapat III Rektor Universitas Bengkulu, Jl WR Supratman, Kandang Limun, Kec Muara Bangka Hulu, Kota Bengkulu</li></ul><p>Dengan narasumber dari *Dinas Pemadam Kebakaran dan Penanggulangan Bencana*, serta *Palang Merah Indonesia*, Kota Bengkulu.&nbsp;<br><br>Dapatkan kesempatan praktik simulasi di samping pemaparan teori untuk topik-topik yang disampaikan. Kamu akan mendapatkan *sertifikat pelatihan resmi dari kedua institusi narasumber*.<br><br>Sasaran peserta khusus workshop ini adalah tenaga kesehatan di klinik, puskesmas dan rumah sakit, pengelola gedung dan para karyawan. Namun masyarakat awam juga bisa ikut sebagai peserta untuk menambah pengetahuan.&nbsp;<br><br>Segera daftarkan diri untuk mengikuti workshop ini karena *kuota terbatas*.<br><br>Info Lebih Lanjut:</p><ul><li><a href=\"https://wa.me/6282213119113\">https://wa.me/6282213119113</a></li><li><a href=\"https://wa.me/6281317950909\">https://wa.me/6281317950909</a></li></ul>','2020-03-10','photo6273905887911455184.jpg',1,'Show'),
(15,'Artikel #','<p>lorem ipsum kkkk</p>','0000-00-00',NULL,NULL,'Unset'),
(16,'artikel ##','<p>lorem ipsum</p>','0000-00-00',NULL,NULL,'Unset');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
